# Generated by Django 4.0 on 2021-12-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kid_name", models.CharField(max_length=200)),
                ("kid_age", models.IntegerField()),
                ("parent_number", models.CharField(max_length=15)),
                ("parent_email_address", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_by", models.CharField(max_length=200)),
                (
                    "food_group",
                    models.CharField(
                        choices=[
                            ("VEG", "Veg"),
                            ("FRUIT", "Fruit"),
                            ("GRAIN", "Grain"),
                            ("PROTEIN", "Protein"),
                            ("DAIRY", "Dairy"),
                            ("CONFECTIONARY", "Confectionary"),
                            ("UNKOWN", "Unknown"),
                        ],
                        default="UNKOWN",
                        max_length=200,
                    ),
                ),
                (
                    "kid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alemeno.kid"
                    ),
                ),
            ],
        ),
    ]
