# Generated by Django 4.0 on 2021-12-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alemeno", "0002_alter_image_created_on_alter_image_updated_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image_url",
        ),
        migrations.AddField(
            model_name="image",
            name="image_field",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
